name: Deploy Docusaurus

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Node.js and npm
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies and build
        run: |
          npm install
          npm run build

      - name: Deploy using Surge
        run: |
          npm install -g surge
          surge build/ youengcode.surge.sh
        env:
          SURGE_LOGIN: ${{ secrets.SURGE_LOGIN }}
          SURGE_TOKEN: ${{ secrets.SURGE_TOKEN }}
